### ISSUE TITLE
Get all NFTs owned by a user

### ISSUE THREAD

**Issue by MakeMake23** [Fusyona/nft-marketplace#75]
Hey @daryckont, the SKALE team proposed we should do this on-chain. It's not a bad idea. 

## On-chain Proposal
Let's deploy a contract with a method as the following:
```solidity
function tokensOfOwner(IERC721 collection, address owner, uint startId, uint endId) 
    view 
    returns (memory uint[]) {
    // if `collection` supports the enumeration extension, then use `tokenOfOwnerByIndex()`;
    // else, just loop from `startId` to `endId` calling `ownerOf()`.
}
```
The method name was inspired by `tokenOfOwnerByIndex()` (see the enumeration extension in [EIP-721](https://eips.ethereum.org/EIPS/eip-721)).
### References
[IERC721Enumerable](https://docs.openzeppelin.com/contracts/5.x/api/token/erc721#IERC721Enumerable), by OpenZeppelin.

## Disclaimer
This issue is a duplication of [web3-core#20](https://github.com/Fusyona/web3-core/issues/20). I think that repo is not stable enough, that's why this issue exists here. It should be moved to there in the future.

**Comment by daryckont** [comment]
@MakeMake23, I think we can try that solution. We talked about this proposal few days ago but was discarded because of an off-chain solution was considered better for it. Just one question: I know this variant is intended for Skale Network, but will this also be applied on the other networks?

**Comment by MakeMake23** [comment]
> @MakeMake23, I think we can try that solution. We talked about this proposal few days ago but was discarded because of an off-chain solution was considered better for it. Just one question: I know this variant is intended for Skale Network, but will this also be applied on the other networks?

I don't remember we discarded this solution, I do remember we did discard a solution involving a modification of the already existing ERC-721 contract, since that's not possible for Nebula right now.

Regarding the extensibility of this solution: I think it doesn't depend on any SKALE peculiarity, so I think it's general enough

**Comment by daryckont** [comment]
Alright, let's make use of it for the rest.

**Comment by daryckont** [comment]
@MakeMake23 we need to define a length for the dynamic array we return from `tokensOfOwner` . Thinking of what is more accurate for this particular case. If we go for a length based on the token balance of the user, chances are that while in the iteration process if the user receives a token when the array reached its end bound it can cause the code to panic. On the other hand if we define to go for a length based on the start and end limits, there is a high probability we return the right token ids followed by a padding of zeroes to fill the array indexes.

**Comment by TheSnakeWitcher** [comment]
Done in #76
